### PR TITLE
[FIX WEBSITE-223] - Index dependency titles

### PR DESCRIPTION
**Pull request by michaelmccaskill**
Index dependency titles and return them as part of a plugin's JSON response.

### CODE REVIEW

**Comment by daniel-beck** [comment]
Looks reasonable AFAIU.

This also gets updated when the application pulls new data from `update-center.json` right? E.g. when a plugin changes display name between releases.

**Comment by michaelmccaskill** [comment]
Correct. Every time the build runs it is first generating new plugin data which it grabs from the update-center.json.

**Comment by daniel-beck** [comment]
It _does_ update every [interval] hours though, right? And that will also update display names? I.e. there's no WEBSITE-224 for the dependency display names?

**Comment by michaelmccaskill** [comment]
The original proposed architecture supported the independent generation of the plugin data, along with the API independently updating its data on an interval. But the decision was made to combine the front and back end into the same container, prior to generating the plugin data. The plugin data is then also wrapped into the same container. Therefore I am unable to tell you accurately how often the plugin data is generated again. You'd have to ask Tyler how often the project is being built and deployed.

**Comment by rtyler** [comment]
@michaelmccaskill The application is being deployed whenever a new tag is deployed (see the [deployment documentation here](https://github.com/jenkins-infra/plugin-site-api#deployment-to-production)), which is to say it is by no means automatic. I should also note that the [DATA_FILE_URL points to ci.jenkins.io](https://github.com/jenkins-infra/jenkins-infra/blob/staging/dist/profile/manifests/pluginsite.pp#L27), which I believe is what was desired.

This project is built based on the criteria in the `Jenkinsfile` in this repository.

**Comment by michaelmccaskill** [comment]
Ok thanks for the explanation.

**Comment by michaelmccaskill** [comment]
Then to do what Daniel is talking about we would need another CI job that only does `mvn -P generatePluginData` and archives that file. Then use that job's "last successful" link as the DATA_FILE_URL. Does that make sense?

**Pull request merged**
