### PR TITLE
Removed sentry from the logs

### LINKED ISSUE #121: Remove Sentry
### Reproduction steps

1. Build

### Expected Results

No Sentry mention in build logs

### Actual Results

Sentry mentions in build logs

### Anything else?

We're not using Sentry anymore, it should be removed.

### PR DESCRIPTION
**Pull request by Gauravpadam**
Closes #121

This removes sentry references from the log

### CODE REVIEW

**Comment by halkeye** [comment]
CI is very very broken atm, i'm not sure we can merge if we wanted to.

**Review by halkeye — APPROVED** [review]

**Comment by lemeurherve** [comment]
I see two other files with references to `sentry`, shouldn't they be updated too?
https://github.com/search?q=repo%3Ajenkins-infra%2Fplugin-site-api%20sentry&type=code

**Comment by Gauravpadam** [comment]
> I see two other files with references to `sentry`, shouldn't they be updated too? https://github.com/search?q=repo%3Ajenkins-infra%2Fplugin-site-api%20sentry&type=code

Sure I'll do that

**Comment by Gauravpadam** [comment]
I've removed all the sentry references from build files, Can you please take a look @lemeurherve?

**Review by lemeurherve — APPROVED** [review]
LGTM

**Comment by lemeurherve** [comment]
Waiting a bit for #120 eventual resolution before merging this PR.

**Review by dduportal — APPROVED** [review]
Thanks 👏

**Pull request merged**
