### PR TITLE
[WEBSITE-648] - Add documentation extractor for arbitrary GitHub URLs

### PR DESCRIPTION
**Pull request by zbynek**
See https://issues.jenkins-ci.org/browse/WEBSITE-648

### CODE REVIEW

**Comment by zbynek** [comment]
This allows documentation URLs to specify both arbitrary path and arbitrary branch of their README file. So in theory it allows plugin maintainers to publish docs only for the released version of their plugin, but that would require changing the branch part of the URL with every release. Deriving the branch automatically from last released version is not in scope of this PR, there is a separate ticket [WEBSITE-641](https://issues.jenkins-ci.org/browse/WEBSITE-641) for that.

**Comment by oleg-nenashev** [comment]
Currently I see 3 cases in http://mirror.serverion.com/jenkins/updates/current/plugin-documentation-urls.json

* https://github.com/jenkinsci/sonar-quality-gates-plugin/blob/master/README.md
* https://github.com/jenkinsci/kryptowire-plugin/tree/master/docs
* https://github.com/jenkinsci/discord-notifier-plugin/blob/master/README.md

AFAICT the  https://github.com/jenkinsci/kryptowire-plugin/tree/master/docs use-case will not be handled by this patch, but we can create a follow-up ticket for that if we consider such use-case important enough

Another interesting use-case would be to have a jenkins.io documentation extractor (e.g. if https://github.com/jenkins-infra/jenkins.io adoc page is referenced), e.g. for BlueOcean. But it is definitely another story

**Comment by oleg-nenashev** [comment]
CC @rsandell @halkeye (comment above)

**Comment by zbynek** [comment]
I don't know how to handle https://github.com/jenkinsci/kryptowire-plugin/tree/master/docs  with one request to the API -- it's possible with two (1. find out whether the folder contains README.md or README.adoc, 2. load the one that exists). If this is not something many plugins would do, then I'd suggest to avoid this URL format.

**Comment by halkeye** [comment]
Why not just let it be provided in the url. GitHub URLs are super standard so easy to parse out whatever data is needed without guessing.

**Comment by zbynek** [comment]
@halkeye yep, if it's provided in the URL it works with this PR already.

@oleg Now I realized that with Maven properties one can define the url as `https://github.com/jenkinsci/repo/blob/tag-${version}/README.md`
which also solves  WEBSITE-461. Question is whether we should also support `https://github.com/jenkinsci/repo/tree/tag-${version}` format as a shortcut for the above (i.e. default readme, but custom branch).

**Comment by oleg-nenashev** [comment]
> Why not just let it be provided in the url. GitHub URLs are super standard so easy to parse out whatever data is needed without guessing.

I'd guess this is what this PR does already. Full URLs will be resolved

> If this is not something many plugins would do, then I'd suggest to avoid this URL format.

+1 , definitely no need to spend time in this PR

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/ssh-credentials-plugin/pull/45 is there for a major plugin, so I will proceed with the release

**Pull request merged**
