### PR TITLE
[WEBSITE-639, WEBSITE-643] - Promote the  #50, #60, #62 to production

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This is a follow-up to #60 which fixes one issue in GitHub pages rendering. #62 also switches GitHub images to CDN. Thanks to @zbybek for the fixes.

Also, it picks up #50 from @daniel-beck which was integrated recently. Should be safe enough

### CODE REVIEW

**Comment by zbynek** [comment]
@oleg-nenashev could you please review #62 and include it here?

**Comment by casz** [comment]
Should help fix https://plugins.jenkins.io/configuration-as-code 😆

**Comment by oleg-nenashev** [comment]
Will merge once the build passes

**Comment by oleg-nenashev** [comment]
https://github.com/jenkins-infra/jenkins-infra/pull/1356 for deployment

**Comment by oleg-nenashev** [comment]
https://github.com/jenkins-infra/plugin-site-api/releases/tag/v1.6.0 for the changelog

**Pull request merged**
