### PR TITLE
[WEBSITE-639] - Missing slash in image URLs

### PR DESCRIPTION
**Pull request by zbynek**
The image URLs seem still wrong after #54 
https://issues.jenkins-ci.org/browse/WEBSITE-406
@oleg-nenashev looped

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@zbynek I'd guess you are referring to https://issues.jenkins-ci.org/browse/WEBSITE-639 , right? Strangeky, it works for some plugins like https://plugins.jenkins.io/folder-auth , but not for others. From what I see it works for in-repo absolute links, but not for relative ones

I'd guess it is just related to the format:

Folder Auth:

```
![Screenshot of the plugin](/docs/images/screenshot.png)
[docs](/docs/usage.md)
```

JCasC Plugin:

```
<img src="plugin/src/main/webapp/img/logo-head.svg" width="192">
```

AFAICT we should support both.

Also CC @AbhyudayaSharma

**Comment by oleg-nenashev** [comment]
Good news is that double-slash links work:

* https://raw.githubusercontent.com/jenkinsci/folder-auth-plugin/master//docs/images/screenshot.png
* https://github.com/jenkinsci/folder-auth-plugin/blob/master//docs/usage.md

It means that this patch will work as is though it is not ideal

**Comment by zbynek** [comment]
@oleg-nenashev thanks, sounds like it may be cleaner to make the changes in https://github.com/jenkins-infra/plugin-site-api/blob/develop/src/main/java/io/jenkins/plugins/services/impl/HttpClientWikiService.java#L137

**Comment by oleg-nenashev** [comment]
@zbynek I confirm the fix images in the documentation entries, but the headshot SVG is still missing:

* Plugin site API returns https://raw.githubusercontent.com/jenkinsci/configuration-as-code-plugin/master/plugin/src/main/webapp/img/logo-head.svg . This is a correct link
* The HTML tag is ``. This is odd, because SVGs should not be rendered in such way. 
* Looks like GitHub just does not not return proper URL for SVGs. 

image

I will create a follow-up JIRA ticket. Maybe just switching the logo to PNG is enough

CC @MarkEWaite @casz @timja

**Comment by zbynek** [comment]
@oleg-nenashev that's a known problem: https://stackoverflow.com/a/18049842
Maybe we should switch to jsdelivr.net to get [proper logo](https://cdn.jsdelivr.net/gh/jenkinsci/configuration-as-code-plugin@master/plugin/src/main/webapp/img/logo-head.svg)

**Comment by daniel-beck** [comment]
FYI I filed [WEBSITE-691](https://issues.jenkins-ci.org/browse/WEBSITE-691) which seems related to this, possibly indicating an incomplete fix.

**Comment by zbynek** [comment]
A proper fix for WEBSITE-691 might need more time, for now I submitted https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/pull/11

**Pull request merged**
